Adds Arquillian cube implementation
forge/addon-arquillian pull request #23
Opened 2017-02-27 10:07 UTC by dipak-pawar

* Added `arquillian-cube-setup` command for docker, docker-compose, openshift, k8s.
* Added command to create a test method if pom.xml any standalone dependency with require cube dependency.

Note: Need to add logic to update test for arquillian resource for openshift.

2017-02-27 10:14 UTC, bartoszmajsak commented
Please rebase on top of master as there are few changes around shell tests

2017-02-27 11:34 UTC, bartoszmajsak commented
Retest this please

2017-02-27 16:13 UTC, bartoszmajsak commented
Add to whitelist

2017-02-28 18:48 UTC, bartoszmajsak requested changes

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeCreateTestCommand.java
> +                    // Do nothing
Maybe just log it? Probably shouldn't happen, but if API enforces exception handling let's spread the word something really odd happen.

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeCreateTestCommand.java
> +                return Results.fail("Could not find arquillian-cube-docker OR arquillian-cube-kuberneters OR arquilliaa-cube-openshift dependency in pom.xml. Please install it using `arquillian-cube-
Will this ever happen? Also error msg has typos.

2017-02-28 18:48 UTC, bartoszmajsak commented on src/test/java/test/integration/cube/CubeCreateTestCommandTest.java
> +        // TODO: 2/27/17 Add Assertion after test logic is done. https://github.com/arquillian/arquillian-cube/issues/608
Shall we first have improvement done in Cube and only then finalize this PR? I've seen a few references in TODOs already.

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/api/ArquillianConfig.java
> +        final Node node = xml.getOrCreate("extension@qualifier=" + qualifier);
We have a lot of duplication with `extension@qualifier=`, `property@name=` - can we make constants out of them? Would it make it simpler?

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/api/ArquillianConfig.java
> +            .orElseThrow(() -> new IllegalStateException("Extension with qaulifier: " + qualifier + " not found."));
Typo: qaulifier

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/api/YamlGenerator.java
> +    public static String getYaml(Map<String, Object> params) {
`toYaml`?

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/api/YamlGenerator.java
> +        // which we don't want in result.
Why not?

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +                return null;
Can `source` be `null`? In which case?

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +        if (msg != null) {
Maybe we should fail before calling `setCubeSetupFacet()` and `setCubeConfigurationParamteres(context)`?

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +        return type.hasValue() && "docker".equals(getStringForCLIDisplay(type.getValue()));
Why do we call `getStringForCLIDisplay` in this case? Shouldn't value be the same from IDE and CLI?

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +    private boolean fileExistsAndisNotDir(UIExecutionContext context, String fileName) {
Can we move the whole file/resource logic to its own component and also unit test it?

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/command/cube/KubernetesCubeTestSetup.java
> +        test.addImport("org.arquillian.cube.kubernetes.annotations.Named");
The reason why we rely on strings is that we don't have it on the classpath at this point?

2017-02-28 18:48 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/container/model/CubeConfiguration.java
> +    private DependencyBuilder dependency;
Make fields final and maybe above the constructor?

2017-02-28 18:48 UTC, bartoszmajsak commented on src/test/java/test/integration/algeron/AddArquillianAlgeronConsumerTest.java
> +        assertThat(project).hasConfiguration().withProperty("contractType", "PACT");
Either soft assert or maybe new method `withProperties(String key, String value, String... keyValuePairs)` ?

2017-02-28 18:48 UTC, bartoszmajsak commented on src/test/java/test/integration/support/assertions/ArquillianConfigAssert.java
> +                Assertions.fail("couldn't find property by name: " + key);
Can we also populate exception here to get more details about what really happened?

2017-03-01 10:15 UTC, lordofthejars requested changes

2017-03-01 10:15 UTC, lordofthejars commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +    private UISelectOne<String> type;
Type means openshift, docker, kubernetes, ... then since it is a known list I would suggest to just change to enum and provide autocompletition

2017-03-01 10:15 UTC, lordofthejars commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +        dockerMachine.setRequired(this::isDockerOrDockerCompose);
Why we have docker machine and machine name? If machine name then there is a docker machine, if not then there is no docker machine. Is this flag somehow redundant?

2017-03-01 10:15 UTC, lordofthejars commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +        machineName.setRequired(this::isDockerMachine);
I will not add this flag as required since Linux developers should be set every to none.

2017-03-01 10:15 UTC, lordofthejars commented on src/test/java/test/integration/cube/CubeSetupCommandTest.java
> +        assertThat(project).hasArquillianConfig().withExtension("docker").withProperty("definitionFormat", "CUBE");
Don't use CUBE format, use always docker-compose format. You can embed it in this property as well.

2017-03-01 10:15 UTC, lordofthejars commented on src/test/java/test/integration/cube/CubeSetupCommandTest.java
> +            "containerName:\n" +
Same as before

2017-03-01 10:15 UTC, lordofthejars commented on src/test/java/test/integration/cube/CubeSetupCommandTest.java
> +            "containerName:\n" +
Same as before

2017-03-01 10:38 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/api/ArquillianConfig.java
> +        final Node node = xml.getOrCreate("extension@qualifier=" + qualifier);
:+1:

2017-03-01 10:40 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/api/ArquillianConfig.java
> +            .orElseThrow(() -> new IllegalStateException("Extension with qaulifier: " + qualifier + " not found."));
good catch

2017-03-01 10:43 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +        return type.hasValue() && "docker".equals(getStringForCLIDisplay(type.getValue()));
From IDE Docker , Docker Compose -> From CLI docker, docker-compose.
I just used it to make comparison easier, so it'll work for both IDE & CLI

2017-03-01 10:44 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/command/cube/KubernetesCubeTestSetup.java
> +        test.addImport("org.arquillian.cube.kubernetes.annotations.Named");
yes right, we don't have that dependency in classpath.

2017-03-01 10:46 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/container/model/CubeConfiguration.java
> +    private DependencyBuilder dependency;
:+1:

2017-03-01 11:00 UTC, dipak-pawar commented on src/test/java/test/integration/support/assertions/ArquillianConfigAssert.java
> +                Assertions.fail("couldn't find property by name: " + key);
Is it a good idea to populate exception in assertion?

2017-03-01 11:01 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +    private UISelectOne<String> type;
It is already provided by using setValueChoices for this option.

2017-03-01 11:02 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/container/model/CubeConfiguration.java
> +    private DependencyBuilder dependency;
:+1:

2017-03-01 11:03 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +        if (msg != null) {
:+1:

2017-03-01 11:13 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +                return null;
no

2017-03-01 11:15 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeCreateTestCommand.java
> +                return Results.fail("Could not find arquillian-cube-docker OR arquillian-cube-kuberneters OR arquilliaa-cube-openshift dependency in pom.xml. Please install it using `arquillian-cube-
yes if user removed this dependency after hitting setup command.

2017-03-01 11:17 UTC, dipak-pawar commented on src/test/java/test/integration/cube/CubeCreateTestCommandTest.java
> +        // TODO: 2/27/17 Add Assertion after test logic is done. https://github.com/arquillian/arquillian-cube/issues/608
yes improvement from cube is done. Now no more To Do's

2017-03-01 11:24 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeCreateTestCommand.java
> +                    // Do nothing
:+1:

2017-03-01 11:26 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/api/YamlGenerator.java
> +    public static String getYaml(Map<String, Object> params) {
Actually we have method with def `toYaml` already in this class. Let make it toYml.

2017-03-01 11:52 UTC, dipak-pawar commented on src/test/java/test/integration/algeron/AddArquillianAlgeronConsumerTest.java
> +        assertThat(project).hasConfiguration().withProperty("contractType", "PACT");
:+1:

2017-03-02 08:32 UTC, bartoszmajsak commented on src/main/java/org/jboss/forge/arquillian/api/YamlGenerator.java
> +        // which we don't want in result as cube yaml parser is not able to parse it.
Shouldn't we fix yaml parser then? Isn't this a standard for yaml?

2017-03-02 09:05 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/api/YamlGenerator.java
> +        // which we don't want in result as cube yaml parser is not able to parse it.
It's not bug. This is specification - http://yaml.org/spec/1.1/#id857168

2017-03-02 13:42 UTC, dipak-pawar commented on src/main/java/org/jboss/forge/arquillian/command/cube/CubeSetupCommand.java
> +    private boolean fileExistsAndisNotDir(UIExecutionContext context, String fileName) {
Added few tests around it.

2017-03-03 05:57 UTC, lordofthejars commented on src/test/java/test/integration/cube/CubeSetupCommandTest.java
> +    @Test(expected = AssertionError.class)
if we are using assertj we can use the `assertThatThrownBy`

2017-03-03 05:57 UTC, lordofthejars commented on src/test/java/test/integration/cube/CubeSetupCommandTest.java
> +    @Test(expected = AssertionError.class)
Same as above

2017-03-03 08:48 UTC, bartoszmajsak commented on src/test/java/test/integration/support/assertions/ArquillianConfigAssert.java
> +                Assertions.fail("couldn't find property by name: " + key);
At least you will know exactly what was the exception thrown.

2017-03-03 12:21 UTC, lordofthejars approved these changes

2017-03-03 12:34 UTC, bartoszmajsak approved these changes

2017-03-03 12:34 UTC, merged