Now using custom assertions for test.
forge/addon-arquillian pull request #28
Opened 2017-03-15 12:05 UTC by dipak-pawar

2017-03-15 18:32 UTC, bartoszmajsak requested changes
Overall nice improvement, thanks for spending time on it! There are just two things I would like you to consider before we merge it.

2017-03-15 18:32 UTC, bartoszmajsak commented on src/test/java/test/integration/algeron/AddArquillianAlgeronRetrieverTest.java
> +            .withProperty("retrieverConfiguration", "provider: folder\ncontractsFolder: /tmp");
I think previous way was more readable. What if we add `\n\n` which should be conceptually irrelevant? We should match strings as such, but key-values, right? Can you think about making it even more pleasant to use?

2017-03-15 18:32 UTC, bartoszmajsak commented on src/test/java/test/integration/support/assertions/ArquillianConfigAssert.java
> +                .orElseThrow(() -> new IllegalStateException("Node with configuration not found."));
Or maybe `AssertionError` instead?

2017-03-16 05:21 UTC, dipak-pawar commented on src/test/java/test/integration/support/assertions/ArquillianConfigAssert.java
> +                .orElseThrow(() -> new IllegalStateException("Node with configuration not found."));
:+1:

2017-03-16 09:33 UTC, bartoszmajsak commented on src/test/java/test/integration/support/assertions/ArquillianConfigAssert.java
> +            final String[] strings = contentOfNode.trim().split("\n");
We create configuration file with new lines using `System.lineSeparator()`. I'm afraid splitting by `\n` would not always work.

2017-03-17 08:03 UTC, bartoszmajsak approved these changes

2017-03-17 08:03 UTC, merged